### ISSUE TITLE
Stop reexporting utils

### ISSUE THREAD

**Issue by aklkv** [hashicorp/consul-ui-toolkit#62]
In cloud-ui we run experimental embroider branch and after this addon was added we started getting build error:

```
WARNING in ../../../../node_modules/@hashicorp/consul-ui-toolkit/dist/_app_/utils/service-list-item.js 1:0-79
export 'default' (reexported as 'default') was not found in '@hashicorp/consul-ui-toolkit/utils/service-list-item' (possible exports: CUT_SERVICE_LIST_ITEM_TYPE, EXTERNAL_SOURCE_ICON_MAPPING, EXTERNAL_SOURCE_LABELS, NORMALIZED_GATEWAY_LABELS, SERVICE_GATEWAY_TYPE)
```

I order to get rid of this error remove `utils` from app reexport as it looks for default export and treas this folder as it would be needed in classic app structure. https://github.com/hashicorp/consul-ui-toolkit/blob/main/toolkit/rollup.config.mjs#L31

**Comment by WenInCode** [comment]
@aklkv I'll get a PR with upgrading the toolkit in cloud-ui to the version that doesn't reexport utils later today

**Comment by aklkv** [comment]
@WenInCode Awesome! Thank you for looking into this 👍🏻
